const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Audio,
		C3.Plugins.Browser,
		C3.Plugins.Keyboard,
		C3.Plugins.LocalStorage,
		C3.Plugins.Touch,
		C3.Plugins.Sprite,
		C3.Behaviors.Fade,
		C3.Behaviors.Tween,
		C3.Behaviors.Flash,
		C3.Behaviors.Sin,
		C3.Behaviors.EightDir,
		C3.Behaviors.Bullet,
		C3.Plugins.TiledBg,
		C3.Plugins.Text,
		C3.Plugins.AJAX,
		C3.Plugins.Button,
		C3.Plugins.SVGPicture,
		C3.Plugins.Json,
		C3.Plugins.Particles,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.System.Exps.choose,
		C3.JavaScriptInEvents.E_game_Event1_Act12,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Text.Cnds.CompareInstanceVar,
		C3.Plugins.System.Exps.zeropad,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.TiledBg.Acts.SetImageOffsetY,
		C3.Plugins.TiledBg.Exps.ImageOffsetY,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Behaviors.EightDir.Acts.SimulateControl,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Particles.Acts.SetRate,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Audio.Acts.SetPlaybackRate,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.SetAnimSpeed,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.System.Acts.Signal,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Plugins.Particles.Acts.SetInitSpeed,
		C3.Plugins.Particles.Acts.SetParticleAcc,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.Compare,
		C3.Behaviors.Sin.Acts.SetPeriod,
		C3.Plugins.Sprite.Exps.AnimationFrameCount,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Cnds.OnSignal,
		C3.Plugins.AJAX.Acts.SetHeader,
		C3.JavaScriptInEvents.E_game_Event66_Act2,
		C3.JavaScriptInEvents.E_game_Event70_Act1
	];
};
self.C3_JsPropNameTable = [
	{Audio: 0},
	{Browser: 0},
	{Keyboard: 0},
	{LocalStorage: 0},
	{Touch: 0},
	{Fade: 0},
	{Tween: 0},
	{Black: 0},
	{Flash: 0},
	{FlashCrash: 0},
	{FlashRecord: 0},
	{Sine: 0},
	{Sine2: 0},
	{"8Direction": 0},
	{Player_Collider: 0},
	{Senóide: 0},
	{Senóide2: 0},
	{Car_Player: 0},
	{Bullet: 0},
	{Explosion: 0},
	{Player_Collider2: 0},
	{Spawn: 0},
	{Cars: 0},
	{Limite: 0},
	{Line_record: 0},
	{Type: 0},
	{Background_1: 0},
	{Background_2: 0},
	{Background_3: 0},
	{Background_4: 0},
	{Background_5: 0},
	{Bt_MobileLeft: 0},
	{Bt_MobileRight: 0},
	{Next_Skin: 0},
	{Next_Skin2: 0},
	{Play: 0},
	{Game_Logo: 0},
	{Text: 0},
	{Spawn_Cars: 0},
	{SpriteRight: 0},
	{ObjectRight: 0},
	{AJAX: 0},
	{GameOverTitle: 0},
	{LeaderboardBtn2: 0},
	{SVGPicture: 0},
	{ScoreText: 0},
	{Asset: 0},
	{Asset2: 0},
	{Asset3: 0},
	{BgGOI: 0},
	{AJAX_Status: 0},
	{JSON: 0},
	{LeaderboardBtn: 0},
	{ObjectLeft: 0},
	{SpriteLeft: 0},
	{RoadAdvert: 0},
	{RoadADS: 0},
	{jalanPantai: 0},
	{Particles: 0},
	{Particles2: 0},
	{SmokeR: 0},
	{SmokeL: 0},
	{SmokeR2: 0},
	{FastEffect: 0},
	{Asset4: 0},
	{Asset5: 0},
	{Asset6: 0},
	{Asset7: 0},
	{PIDText: 0},
	{Text2: 0},
	{Menu: 0},
	{Bg: 0},
	{Buttons: 0},
	{Direction: 0},
	{Score: 0},
	{Best: 0},
	{SpawnTime: 0},
	{SpeedCars: 0},
	{SpeedBackground: 0},
	{StartGame: 0},
	{Backgrounds: 0},
	{SkinSelected: 0},
	{CarAlive: 0},
	{Data: 0},
	{params: 0},
	{ID_user: 0},
	{ID_game: 0},
	{mobileNumber: 0},
	{token: 0},
	{transactionID: 0},
	{gamemodeID: 0},
	{isLeftTouchEnable: 0},
	{isRightTouchEnable: 0}
];

self.InstanceType = {
	Audio: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	Fade: class extends self.ISpriteInstance {},
	Black: class extends self.ISpriteInstance {},
	FlashCrash: class extends self.ISpriteInstance {},
	FlashRecord: class extends self.ISpriteInstance {},
	Player_Collider: class extends self.ISpriteInstance {},
	Car_Player: class extends self.ISpriteInstance {},
	Explosion: class extends self.ISpriteInstance {},
	Player_Collider2: class extends self.ISpriteInstance {},
	Spawn: class extends self.ISpriteInstance {},
	Cars: class extends self.ISpriteInstance {},
	Limite: class extends self.ISpriteInstance {},
	Line_record: class extends self.ISpriteInstance {},
	Background_1: class extends self.ITiledBackgroundInstance {},
	Background_2: class extends self.ITiledBackgroundInstance {},
	Background_3: class extends self.ITiledBackgroundInstance {},
	Background_4: class extends self.ITiledBackgroundInstance {},
	Background_5: class extends self.ITiledBackgroundInstance {},
	Bt_MobileLeft: class extends self.ISpriteInstance {},
	Bt_MobileRight: class extends self.ISpriteInstance {},
	Next_Skin: class extends self.ISpriteInstance {},
	Next_Skin2: class extends self.ISpriteInstance {},
	Play: class extends self.ISpriteInstance {},
	Game_Logo: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	Spawn_Cars: class extends self.ISpriteInstance {},
	SpriteRight: class extends self.ISpriteInstance {},
	ObjectRight: class extends self.ISpriteInstance {},
	AJAX: class extends self.IInstance {},
	GameOverTitle: class extends self.ITextInstance {},
	LeaderboardBtn2: class extends self.IButtonInstance {},
	SVGPicture: class extends self.ISVGPictureInstance {},
	ScoreText: class extends self.ITextInstance {},
	Asset: class extends self.ISpriteInstance {},
	Asset2: class extends self.ISpriteInstance {},
	Asset3: class extends self.ISpriteInstance {},
	BgGOI: class extends self.ISpriteInstance {},
	AJAX_Status: class extends self.ITextInstance {},
	JSON: class extends self.IJSONInstance {},
	LeaderboardBtn: class extends self.ISpriteInstance {},
	ObjectLeft: class extends self.ISpriteInstance {},
	SpriteLeft: class extends self.ISpriteInstance {},
	RoadAdvert: class extends self.ISpriteInstance {},
	RoadADS: class extends self.ISpriteInstance {},
	jalanPantai: class extends self.ISpriteInstance {},
	Particles: class extends self.IParticlesInstance {},
	Particles2: class extends self.IParticlesInstance {},
	SmokeR: class extends self.IParticlesInstance {},
	SmokeL: class extends self.IParticlesInstance {},
	SmokeR2: class extends self.IParticlesInstance {},
	FastEffect: class extends self.IParticlesInstance {},
	Asset4: class extends self.ISpriteInstance {},
	Asset5: class extends self.ISpriteInstance {},
	Asset6: class extends self.ISpriteInstance {},
	Asset7: class extends self.ISpriteInstance {},
	PIDText: class extends self.ITextInstance {},
	Text2: class extends self.ITextInstance {},
	Menu: class extends self.ISpriteInstance {},
	Bg: class extends self.ITiledBackgroundInstance {},
	Buttons: class extends self.ISpriteInstance {}
}